"""empty message

Revision ID: 8b0aaddb1609
Revises: 
Create Date: 2020-05-26 09:06:42.360429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0aaddb1609'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Accounts_email'), 'Accounts', ['email'], unique=True)
    op.create_index(op.f('ix_Accounts_id'), 'Accounts', ['id'], unique=False)
    op.create_index(op.f('ix_Accounts_username'), 'Accounts', ['username'], unique=True)
    op.create_table('Clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('oname', sa.String(), nullable=True),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('apart_no', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('estate', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Clients_id'), 'Clients', ['id'], unique=False)
    op.create_table('Services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Services_id'), 'Services', ['id'], unique=False)
    op.create_table('Installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['Clients.id'], ),
    sa.ForeignKeyConstraint(['service'], ['Services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Installations_id'), 'Installations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Installations_id'), table_name='Installations')
    op.drop_table('Installations')
    op.drop_index(op.f('ix_Services_id'), table_name='Services')
    op.drop_table('Services')
    op.drop_index(op.f('ix_Clients_id'), table_name='Clients')
    op.drop_table('Clients')
    op.drop_index(op.f('ix_Accounts_username'), table_name='Accounts')
    op.drop_index(op.f('ix_Accounts_id'), table_name='Accounts')
    op.drop_index(op.f('ix_Accounts_email'), table_name='Accounts')
    op.drop_table('Accounts')
    # ### end Alembic commands ###
