"""empty message

Revision ID: 93b704581e47
Revises: 28db0ca52978
Create Date: 2020-05-25 02:24:44.337347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b704581e47'
down_revision = '28db0ca52978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'email')
    # ### end Alembic commands ###
