"""empty message

Revision ID: f3511e3192d8
Revises: 82a1a92a0849
Create Date: 2020-06-09 09:53:50.889900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3511e3192d8'
down_revision = '82a1a92a0849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Installations', sa.Column('installed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Installations', 'installed')
    # ### end Alembic commands ###
